config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'

  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  get "search" => "searches#search"

  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true,length: { maximum: 200 }

  #検索方法分岐
  def self.looks(search,word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}")
    else
      @book = Book.all
    end
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # class_name: "User"でUserモデルを参照
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  #フォローをされた時の関係
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  #フォローをしたときの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  validates :name,presence: true,uniqueness:true,
                  length: { minimum: 2, maximum: 20 }
  validates :introduction,length: { maximum: 50 }

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

  #フォローをしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  #フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  #フォローしているか判断
  def following?(user)
    followings.include?(user)
  end

  #検索方法分岐
  def self.looks(search,word)
    if search == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}")
    else
      @user = User.all
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @books = Book.all
    @user = current_user
    if @book.save
      flash[:notice] = "You have created book successfully"
      redirect_to book_path(@book.id)
    else
      render "index"
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.new
    @book_show = Book.find(params[:id])
    @user = @book_show.user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
       render :edit
    end
  end

  def destroy
    @book_show = Book.find(params[:id])
    @book_show.delete
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  #フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  #フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  #フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  #フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  #if文を使い検索モデルUser or Bookで条件分岐
  def search
    @range = params[:range]
    @word =  params[:word]

    if @range == "User"
      @users = User.looks(params[:search],params[:word])
    else
      @books = Book.looks(params[:search],params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book = Book.new
    @user = current_user
    @users = User.all
    
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user== current_user
      render"edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
     render:edit
    end
  end

 private
  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
 <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image.variant(resize: "80x80!") %>
            <% end %>
          </td>
          <td>
          <%= link_to book_path(book.id) do %>
          <%= book.title %>
          <% end %>
          </td>
          <td><%= book.body %></td>
          <td colspan="3"></td>
        </tr>
        <% end %>
        </tbody>
      </table>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:%>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <p>Title</p>
          <p><%= f.text_field :title %></p>
        </div>

        <div class="form-group">
          <p>Opinion</p>
          <p><%= f.text_area :body %></p>
        </div>


        <div class="form-group">
         <%= f.submit 'Update Book' %>
        </div>
      <% end %>


      <%= link_to "Show",book_path(@book.id) %>|
      <%= link_to "Back",books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: @user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image.variant(resize: "80x80!") %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
              <td colspan="3"></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h2>User info</h2>
<%= form_with model: @book_image do |f| %>
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <h4>Title</h4>
  <%= f.text_field :shop_name %>
  <h4>Opinion</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: @user,book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= image_tag @user.get_profile_image.variant(resize: "100x100!") %>
                <p><%= @user.name %></p>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book_show.id) do %>
                <%= @book_show.title %>
              <% end %>
            </td>
            <td>
              <%= @book_show.body %>
            </td>
            <% if @user == current_user %>
              <td>
                <%= link_to "Edit",edit_book_path(@book_show.id), class: 'btn btn-sm btn-outline-success' %>
              </td>
              <td>
                <%= link_to "Destroy",book_path(@book_show.id),method: :delete, "data-confirm" => "本当に消しますか？",class: 'btn btn-sm btn-outline-danger' %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to<i class="fas fa-book"></i>
      <strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to<i class="fas fa-book"></i>
        <strong>Bookers</strong> !!
      </h1>
      <p>In<i class="fas fa-book"></i>
        <strong>Bookers</strong>,
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</P>
    </div>
  </div>

  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i>Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i>Users
              <% end %>
            </li>
            <li>
              <%= link_to books_path, class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i>Books
              <% end %>
            </li>
            <li>
              <%= link_to '/users/sign_out', class: 'nav-link text-light', :method => :delete do %>
              <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
            </li>

            <% else %>
              <li>
                <%= link_to root_path, class: 'nav-link text-light' do %>
                 <i class="fas fa-home"></i>Home
                 <% end %>
              </li>
              <li>
                <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i>About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class= "fas fa-sign-in-alt"></i>Log in
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <%= render 'searches/search' %>
    </header>
    <%= flash[:notice] %>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/searches/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path,local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'],['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-outline-primary" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
    <h3>Users search for "<%= @word %>"</h3>
    <%= render 'users/index', user: @users %>
  <!--検索対象モデルがUserではない時(= 検索対象モデルがBookの時) -->
  <% else @range == "Book" %>
    <h3>Books search for "<%= @word %>"</h3>
    <%= render 'books/index', books: @books %>
  <% end %>

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% user.each do |user| %>
      <tr>
        <td>
          <%= image_tag user.get_profile_image.variant(resize: "80x80!") %>
        </td>
        <td>
          <%= link_to user.name, user_path(user.id) %>
        </td>
        <td>フォロー数 <%= user.followings.count %></td>
        <td>フォロワー数 <%= user.followers.count %></td>

        <% if user != current_user %>
          <% if current_user.following?(user) %>
            <td><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></td>
          <% else %>
            <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
          <% end %>
        <% end %>

        <td>
          <%= link_to "Show", user_path(user.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_list.html.erb
<div class="text-dark"></div>

<h2>User info</h2>
<%= image_tag user.get_profile_image.variant(resize: "100x100!") %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>

    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>

    <tr>
      <th>follow</th>
      <th><%= user.followings.count %></th>
    </tr>

    <tr>
      <th>followers</th>
      <th><%= user.followers.count %></th>
    </tr>
  </tbody>
</table>


<% if user != current_user %>
  <% if current_user.following?(user) %>
    <td><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete,class: 'btn btn-outline-primary'%></td>
  <% else %>
    <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post,class: 'btn btn-sm btn-outline-success'%></td>
  <%end %>
<% end %>

<div class="row">
  <%= link_to edit_user_path(user.id), class: 'btn btn-outline-secondary btn-block' do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

<h2 class="mt-3">New book</h2>
<from action="/books" accept-charset="UTF-8" method="post">
  <%= form_with model:@book do |f| %>
    <div class="from-group">
      <p>Title</p>
      <p><%= f.text_field :title %></p>
    </div>

    <div class="from-group">
      <p>Opinion</p>
      <%= f.text_area :body %>
    </div>

    <div class="from-group">
      <%= f.submit 'Create Book',class: 'btn btn-sm btn-outline-success'%>
    </div>
  <% end %>
</from>

app/views/users/edit.html.erb
<%= form_with model: @user, url: user_path(@user.id), method: :patch do |f| %>
  <% if @user.errors.any? %>
    <%= @user.errors.count %> error prohibited this obj from being saved:
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>


<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <p><%= f.text_field :name %></p>
        </div>

        <div class="form-group">
          <label for="user_image">Image</label>
          <p><%= f.file_field :profile_image, accept: "image/*" %></p>
        </div>

        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <p><%= f.text_area :introduction %></p>
        </div>
        <div class="form-group">
          <p><%= f.submit "Update User", class: 'btn btn-outline-secondary'%></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'list', user: @user,book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= image_tag user.get_profile_image.variant(resize: "80x80!") %>
              </td>
              <td>
                <%= link_to user.name, user_path(user.id) %>
              </td>
              <td>フォロー数 <%= user.followings.count %></td>
              <td>フォロワー数 <%= user.followers.count %></td>
              <% if user != current_user %>
                <% if current_user.following?(user) %>
                  <td><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></td>
                <% else %>
                  <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
                <% end %>
              <% end %>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'list', user: @user,book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |books| %>
            <tr>
              <td>
                <%= link_to user_path(books.user_id) do %>
                  <%= image_tag books.user.get_profile_image.variant(resize: "80x80!") %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(books.id) do %>
                  <%= books.title %>
                <% end %>
              </td>
              <td><%= books.body %></td>
              <td></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>